# Generated by Django 4.2.11 on 2024-06-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='mysite/pictures/profile_pictures/user.png', upload_to='profile_pictures'),
        ),
    ]
