# Generated by Django 4.2.11 on 2024-06-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/home/kishor/Downloads/user.png', upload_to='profile_pictures'),
        ),
    ]
